version: '3.8'

services:
  gameoflife:
    build:
      context: .
      dockerfile: Dockerfile
    image: gameoflife
    container_name: gameoflife8
    ports:
      - "8090:8080"
    stdin_open: true
    tty: true
    restart: always
